# The Site Configuration

theme: jekyll-theme-chirpy
url: 'https://jexxers.github.io'
baseurl: ''
lang: en-US # https://www.w3.org/International/questions/qa-choosing-language-tags
timezone: America/Toronto # http://www.timezoneconverter.com/cgi-bin/findzone/findzone
title: Thoughtlot
tagline: I just can't get you out of my head.  Mind, your thoughts is all I think about.

description: >-                        # used by seo meta and the atom feed
  Life.  Tech.  Reflections.

author: Jess Leung
avatar: assets/images/avatar.jpg
toc: true
github:
  username: jexxers
twitter:
  username: jexxers
social:
  name: Jess Leung
  email: example@doamin.com             # change to your email address
  links:
    - https://twitter.com/jexxers
    - https://github.com/jexxers

google_site_verification: google_meta_tag_verification # change to your verification string
google_analytics:
  id: ''  
  pv:
    enabled: false
    proxy_url: ''
    proxy_endpoint: ''
    cache: false

theme_mode:   dark

# The CDN endpoint for images.
# Notice that once it is assigned, the CDN url
# will be added to all image (site avatar & posts' images) paths starting with '/'
#
# e.g. 'https://cdn.com'
img_cdn: ''


disqus:
  comments: false  # boolean type, the global switch for posts comments.
  shortname: ''    # Fill with your Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname

paginate: 10

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:   # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# DO NOT change this unless you're a Pro user on Jekyll and Web development,
# Or you think you're smart enough to change other relevant URLs within this template.
permalink: /posts/:title/

collections:
  tabs:
    output: true
    sort_by: order


defaults:
  -
    scope:
      path: ''          # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true    # Enable comments in posts.
      toc: true         # Display TOC column in posts.
  -
    scope:
      path: _drafts
    values:
      comments: false
  -
    scope:
      path: ''
      type: tabs             # see `site.collections`
    values:
      layout: page
      permalink: /:title/
      dynamic_title: true    # Hide title in mobile screens.

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - '*.gem'
  - '*.gemspec'
  - tools
  - docs
  - README.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - package.json
  - package-lock.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
